"""add_sector_type_to_tenants

Revision ID: d67bd5951ff1
Revises: 
Create Date: 2026-07-12 17:28:44.547748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67bd5951ff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tenants', sa.Column('sector_type', sa.String(length=50), nullable=False, server_default='generic'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'sector_type')
    # ### end Alembic commands ###
